export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ENABLE_2FA_BEGIN = 'ENABLE_2FA_BEGIN';
export const ENABLE_2FA_SUCCESS = 'ENABLE_2FA_SUCCESS';
export const ENABLE_2FA_FAIL = 'ENABLE_2FA_FAIL';
export const ENABLE_2FA_IDLE = 'ENABLE_2FA_IDLE';

export const DISABLE_2FA_BEGIN = 'DISABLE_2FA_BEGIN';
export const DISABLE_2FA_SUCCESS = 'DISABLE_2FA_SUCCESS';
export const DISABLE_2FA_FAIL = 'DISABLE_2FA_FAIL';
export const DISABLE_2FA_IDLE = 'DISABLE_2FA_IDLE';

export const CHANGE_USER_TFA_STATE = 'CHANGE_USER_TFA_STATE';
export const AUTH_USER_TFA = 'AUTH_USER_TFA';

export const THEME_TOGGLE = 'THEME_TOGGLE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_NODESTATUS_BEGIN = 'FETCH_NODESTATUS_BEGIN';
export const FETCH_NODESTATUS_SUCCESS = 'FETCH_NODESTATUS_SUCCESS';
export const FETCH_NODESTATUS_FAIL = 'FETCH_NODESTATUS_FAIL';

export const FETCH_SERVERS_BEGIN = 'FETCH_SERVERS_BEGIN';
export const FETCH_SERVERS_SUCCESS = 'FETCH_SERVERS_SUCCESS';
export const FETCH_SERVERS_FAIL = 'FETCH_SERVERS_FAIL';

