export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ENABLE_2FA_BEGIN = 'ENABLE_2FA_BEGIN';
export const ENABLE_2FA_SUCCESS = 'ENABLE_2FA_SUCCESS';
export const ENABLE_2FA_FAIL = 'ENABLE_2FA_FAIL';
export const ENABLE_2FA_IDLE = 'ENABLE_2FA_IDLE';

export const DISABLE_2FA_BEGIN = 'DISABLE_2FA_BEGIN';
export const DISABLE_2FA_SUCCESS = 'DISABLE_2FA_SUCCESS';
export const DISABLE_2FA_FAIL = 'DISABLE_2FA_FAIL';
export const DISABLE_2FA_IDLE = 'DISABLE_2FA_IDLE';

export const CHANGE_USER_TFA_STATE = 'CHANGE_USER_TFA_STATE';
export const AUTH_USER_TFA = 'AUTH_USER_TFA';

export const THEME_TOGGLE = 'THEME_TOGGLE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_NODESTATUS_BEGIN = 'FETCH_NODESTATUS_BEGIN';
export const FETCH_NODESTATUS_SUCCESS = 'FETCH_NODESTATUS_SUCCESS';
export const FETCH_NODESTATUS_FAIL = 'FETCH_NODESTATUS_FAIL';

export const FETCH_SERVERS_BEGIN = 'FETCH_SERVERS_BEGIN';
export const FETCH_SERVERS_SUCCESS = 'FETCH_SERVERS_SUCCESS';
export const FETCH_SERVERS_FAIL = 'FETCH_SERVERS_FAIL';

export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_ACTIVITY_BEGIN = 'FETCH_ACTIVITY_BEGIN';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAIL = 'FETCH_ACTIVITY_FAIL';
export const INSERT_ACTIVITY = 'INSERT_ACTIVITY';

export const FETCH_DEPOSITS_BEGIN = 'FETCH_DEPOSITS_BEGIN';
export const FETCH_DEPOSITS_SUCCESS = 'FETCH_DEPOSITS_SUCCESS';
export const FETCH_DEPOSITS_FAIL = 'FETCH_DEPOSITS_FAIL';

export const FETCH_WITHDRAWALS_BEGIN = 'FETCH_WITHDRAWALS_BEGIN';
export const FETCH_WITHDRAWALS_SUCCESS = 'FETCH_WITHDRAWALS_SUCCESS';
export const FETCH_WITHDRAWALS_FAIL = 'FETCH_WITHDRAWALS_FAIL';

export const FETCH_DASHBOARDUSERS_BEGIN = 'FETCH_DASHBOARDUSERS_BEGIN';
export const FETCH_DASHBOARDUSERS_SUCCESS = 'FETCH_DASHBOARDUSERS_SUCCESS';
export const FETCH_DASHBOARDUSERS_FAIL = 'FETCH_DASHBOARDUSERS_FAIL';

export const FETCH_CHANNELS_BEGIN = 'FETCH_CHANNELS_BEGIN';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAIL = 'FETCH_CHANNELS_FAIL';

export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';
export const UPDATE_SERVER = 'UPDATE_SERVER';
export const UPDATE_USER = 'UPDATE_USER';

export const FETCH_FEATURES_BEGIN = 'FETCH_FEATURES_BEGIN';
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS';
export const FETCH_FEATUERS_FAIL = 'FETCH_FEATUERS_FAIL';
export const UPDATE_FEATURE = 'UPDATE_FEATURE';
export const REMOVE_FEATURE = 'REMOVE_FEATURE';
export const ADD_FEATURE = 'ADD_FEATURE';

export const DECLINE_WITHDRAWAL_BEGIN = 'DECLINE_WITHDRAWAL_BEGIN';
export const DECLINE_WITHDRAWAL_SUCCESS = 'DECLINE_WITHDRAWAL_SUCCESS';
export const DECLINE_WITHDRAWAL_FAIL = 'DECLINE_WITHDRAWAL_FAIL';
export const ACCEPT_WITHDRAWAL_FAIL = 'ACCEPT_WITHDRAWAL_FAIL';
export const ACCEPT_WITHDRAWAL_SUCCESS = 'ACCEPT_WITHDRAWAL_SUCCESS';
export const ACCEPT_WITHDRAWAL_BEGIN = 'ACCEPT_WITHDRAWAL_BEGIN';

export const UPDATE_WITHDRAWAL = 'UPDATE_WITHDRAWAL';

export const FETCH_BOTSETTINGS_BEGIN = 'FETCH_BOTSETTINGS_BEGIN';
export const FETCH_BOTSETTINGS_SUCCESS = 'FETCH_BOTSETTINGS_SUCCESS';
export const FETCH_BOTSETTINGS_FAIL = 'FETCH_BOTSETTINGS_FAIL';
export const UPDATE_BOTSETTINGS = 'UPDATE_BOTSETTINGS';

export const PATCH_DEPOSITS_BEGIN = 'PATCH_DEPOSITS_BEGIN';
export const PATCH_DEPOSITS_SUCCESS = 'PATCH_DEPOSITS_SUCCESS';
export const PATCH_DEPOSITS_FAIL = 'PATCH_DEPOSITS_FAIL';

export const FETCH_BLOCKNUMBER_BEGIN = 'FETCH_BLOCKNUMBER_BEGIN';
export const FETCH_BLOCKNUMBER_SUCCESS = 'FETCH_BLOCKNUMBER_SUCCESS';
export const FETCH_BLOCKNUMBER_FAIL = 'FETCH_BLOCKNUMBER_FAIL';

export const FETCH_TRIVIAQUESTIONS_BEGIN = 'FETCH_TRIVIAQUESTIONS_BEGIN';
export const FETCH_TRIVIAQUESTIONS_SUCCESS = 'FETCH_TRIVIAQUESTIONS_SUCCESS';
export const FETCH_TRIVIAQUESTIONS_FAIL = 'FETCH_TRIVIAQUESTIONS_FAIL';

export const INSERT_TRIVIA_BEGIN = 'INSERT_TRIVIA_BEGIN';
export const INSERT_TRIVIA_SUCCESS = 'INSERT_TRIVIA_SUCCESS';
export const INSERT_TRIVIA_FAIL = 'INSERT_TRIVIA_FAIL';

export const REMOVE_TRIVIA_BEGIN = 'REMOVE_TRIVIA_BEGIN';
export const REMOVE_TRIVIA_SUCCESS = 'REMOVE_TRIVIA_SUCCESS';
export const REMOVE_TRIVIA_FAIL = 'REMOVE_TRIVIA_FAIL';

export const SWITCH_TRIVIA_BEGIN = 'SWITCH_TRIVIA_BEGIN';
export const SWITCH_TRIVIA_SUCCESS = 'SWITCH_TRIVIA_SUCCESS';
export const SWITCH_TRIVIA_FAIL = 'SWITCH_TRIVIA_FAIL';

export const DELETE_TRIVIAQUESTION = 'DELETE_TRIVIAQUESTION';
export const ADD_TRIVIAQUESTION = 'ADD_TRIVIAQUESTION';

export const FETCH_ERRORS_BEGIN = 'FETCH_ERRORS_BEGIN';
export const FETCH_ERRORS_SUCCESS = 'FETCH_ERRORS_SUCCESS';
export const FETCH_ERRORS_FAIL = 'FETCH_ERRORS_FAIL';

export const FETCH_PRICECURRENCIES_BEGIN = 'FETCH_PRICECURRENCIES_BEGIN';
export const FETCH_PRICECURRENCIES_SUCCESS = 'FETCH_PRICECURRENCIES_SUCCESS';
export const FETCH_PRICECURRENCIES_FAIL = 'FETCH_PRICECURRENCIES_FAIL';
export const UPDATE_PRICECURRENCIES = 'UPDATE_PRICECURRENCIES';
export const REMOVE_PRICECURRENCIES = 'REMOVE_PRICECURRENCIES';
export const ADD_PRICECURRENCIES = 'ADD_PRICECURRENCIES';

export const FETCH_USERINFO_BEGIN = 'FETCH_USERINFO_BEGIN';
export const FETCH_USERINFO_SUCCESS = 'FETCH_USERINFO_SUCCESS';
export const FETCH_USERINFO_FAIL = 'FETCH_USERINFO_FAIL';

export const FETCH_WITHDRAWALADDRESSES_BEGIN = 'FETCH_WITHDRAWALADDRESSES_BEGIN';
export const FETCH_WITHDRAWALADDRESSES_SUCCESS = 'FETCH_WITHDRAWALADDRESSES_SUCCESS';
export const FETCH_WITHDRAWALADDRESSES_FAIL = 'FETCH_WITHDRAWALADDRESSES_FAIL';

export const FETCH_WITHDRAWALADDRESS_BEGIN = 'FETCH_WITHDRAWALADDRESS_BEGIN';
export const FETCH_WITHDRAWALADDRESS_SUCCESS = 'FETCH_WITHDRAWALADDRESS_SUCCESS';
export const FETCH_WITHDRAWALADDRESS_FAIL = 'FETCH_WITHDRAWALADDRESS_FAIL';

export const FETCH_BOTFUNCTION_BEGIN = 'FETCH_BOTFUNCTION_BEGIN';
export const FETCH_BOTFUNCTION_SUCCESS = 'FETCH_BOTFUNCTION_SUCCESS';
export const FETCH_BOTFUNCTION_FAIL = 'FETCH_BOTFUNCTION_FAIL';

export const FETCH_BOTFUNCTIONS_BEGIN = 'FETCH_BOTFUNCTIONS_BEGIN';
export const FETCH_BOTFUNCTIONS_SUCCESS = 'FETCH_BOTFUNCTIONS_SUCCESS';
export const FETCH_BOTFUNCTIONS_FAIL = 'FETCH_BOTFUNCTIONS_FAIL';

export const POST_LEAVESERVER_BEGIN = 'POST_LEAVESERVER_BEGIN';
export const POST_LEAVESERVER_SUCCESS = 'POST_LEAVESERVER_SUCCESS';
export const POST_LEAVESERVER_FAIL = 'POST_LEAVESERVER_FAIL';
export const POST_LEAVESERVER = 'POST_LEAVESERVER';

export const FETCH_DP_BEGIN = 'FETCH_DP_BEGIN';
export const FETCH_DP_SUCCESS = 'FETCH_DP_SUCCESS';
export const FETCH_DP_FAIL = 'FETCH_DP_FAIL';

export const FETCH_ADMINWALLET_BEGIN = 'FETCH_ADMINWALLET_BEGIN';
export const FETCH_ADMINWALLET_SUCCESS = 'FETCH_ADMINWALLET_SUCCESS';
export const FETCH_ADMINWALLET_FAIL = 'FETCH_ADMINWALLET_FAIL';

export const FETCH_COINS_BEGIN = 'FETCH_COINS_BEGIN';
export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COINS_FAIL = 'FETCH_COINS_FAIL';

export const EDIT_COININFO_BEGIN = 'EDIT_COININFO_BEGIN';
export const EDIT_COININFO_SUCCESS = 'EDIT_COININFO_SUCCESS';
export const EDIT_COININFO_FAIL = 'EDIT_COININFO_FAIL';

export const UPDATE_COIN = 'UPDATE_COIN';

export const DELETE_COININFOEXCHANGE_BEGIN = 'DELETE_COININFOEXCHANGE_BEGIN';
export const DELETE_COININFOEXCHANGE_SUCCESS = 'DELETE_COININFOEXCHANGE_SUCCESS';
export const DELETE_COININFOEXCHANGE_FAIL = 'DELETE_COININFOEXCHANGE_FAIL';

export const UPDATE_TRIVIA_QUESTION = 'UPDATE_TRIVIA_QUESTION';
export const UPDATE_TRIVIA_ANSWER = 'UPDATE_TRIVIA_ANSWER';

export const DELETE_COININFOHINT_BEGIN = 'DELETE_COININFOHINT_BEGIN';
export const DELETE_COININFOHINT_SUCCESS = 'DELETE_COININFOHINT_SUCCESS';
export const DELETE_COININFOHINT_FAIL = 'DELETE_COININFOHINT_FAIL';
