export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR';
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const ENABLE_2FA_BEGIN = 'ENABLE_2FA_BEGIN';
export const ENABLE_2FA_SUCCESS = 'ENABLE_2FA_SUCCESS';
export const ENABLE_2FA_FAIL = 'ENABLE_2FA_FAIL';
export const ENABLE_2FA_IDLE = 'ENABLE_2FA_IDLE';

export const DISABLE_2FA_BEGIN = 'DISABLE_2FA_BEGIN';
export const DISABLE_2FA_SUCCESS = 'DISABLE_2FA_SUCCESS';
export const DISABLE_2FA_FAIL = 'DISABLE_2FA_FAIL';
export const DISABLE_2FA_IDLE = 'DISABLE_2FA_IDLE';

export const CHANGE_USER_TFA_STATE = 'CHANGE_USER_TFA_STATE';
export const AUTH_USER_TFA = 'AUTH_USER_TFA';

export const THEME_TOGGLE = 'THEME_TOGGLE';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

export const FETCH_NODESTATUS_BEGIN = 'FETCH_NODESTATUS_BEGIN';
export const FETCH_NODESTATUS_SUCCESS = 'FETCH_NODESTATUS_SUCCESS';
export const FETCH_NODESTATUS_FAIL = 'FETCH_NODESTATUS_FAIL';

export const FETCH_SERVERS_BEGIN = 'FETCH_SERVERS_BEGIN';
export const FETCH_SERVERS_SUCCESS = 'FETCH_SERVERS_SUCCESS';
export const FETCH_SERVERS_FAIL = 'FETCH_SERVERS_FAIL';

export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_ACTIVITY_BEGIN = 'FETCH_ACTIVITY_BEGIN';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_FAIL = 'FETCH_ACTIVITY_FAIL';
export const INSERT_ACTIVITY = 'INSERT_ACTIVITY';

export const FETCH_DEPOSITS_BEGIN = 'FETCH_DEPOSITS_BEGIN';
export const FETCH_DEPOSITS_SUCCESS = 'FETCH_DEPOSITS_SUCCESS';
export const FETCH_DEPOSITS_FAIL = 'FETCH_DEPOSITS_FAIL';

export const FETCH_WITHDRAWALS_BEGIN = 'FETCH_WITHDRAWALS_BEGIN';
export const FETCH_WITHDRAWALS_SUCCESS = 'FETCH_WITHDRAWALS_SUCCESS';
export const FETCH_WITHDRAWALS_FAIL = 'FETCH_WITHDRAWALS_FAIL';

export const FETCH_DASHBOARDUSERS_BEGIN = 'FETCH_DASHBOARDUSERS_BEGIN';
export const FETCH_DASHBOARDUSERS_SUCCESS = 'FETCH_DASHBOARDUSERS_SUCCESS';
export const FETCH_DASHBOARDUSERS_FAIL = 'FETCH_DASHBOARDUSERS_FAIL';

export const FETCH_LIABILITY_BEGIN = 'FETCH_LIABILITY_BEGIN';
export const FETCH_LIABILITY_SUCCESS = 'FETCH_LIABILITY_SUCCESS';
export const FETCH_LIABILITY_FAIL = 'FETCH_LIABILITY_FAIL';

export const FETCH_BALANCE_BEGIN = 'FETCH_BALANCE_BEGIN';
export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS';
export const FETCH_BALANCE_FAIL = 'FETCH_BALANCE_FAIL';

export const FETCH_CHANNELS_BEGIN = 'FETCH_CHANNELS_BEGIN';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAIL = 'FETCH_CHANNELS_FAIL';

export const UPDATE_CHANNEL = 'UPDATE_CHANNEL';
export const UPDATE_SERVER = 'UPDATE_SERVER';
export const UPDATE_USER = 'UPDATE_USER';
